services:
  app:
    build:
      context: "."
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
      - "3002:3002"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - CHROME_PATH=/usr/bin/google-chrome-stable # In case it's needed for puppeteer
    stdin_open: true
    tty: true
