import { beforeEach, describe, expect, it, vi } from 'vitest';

const pagePdf = vi.fn();
const pageClose = vi.fn();
const browserClose = vi.fn();
const browserNewPage = vi.fn();
const puppeteerLaunch = vi.fn();
const s3Send = vi.fn();
const pageOn = vi.fn();

vi.mock('puppeteer-core', () => ({
  default: {
    launch: puppeteerLaunch,
  },
}));

vi.mock('@sparticuz/chromium', () => ({
  default: {
    args: ['--no-sandbox'],
    defaultViewport: { width: 794, height: 1122 },
    executablePath: vi.fn(async () => '/tmp/chromium'),
    headless: true,
  },
}));

vi.mock('@aws-sdk/client-s3', () => ({
  GetObjectCommand: vi.fn(function GetObjectCommand(input) {
    return { input };
  }),
  S3Client: vi.fn(function S3Client() {
    return { send: s3Send };
  }),
}));

const makePage = () => ({
  setRequestInterception: vi.fn(),
  on: pageOn,
  setViewport: vi.fn(),
  setContent: vi.fn(),
  evaluate: vi.fn(),
  pdf: pagePdf,
  close: pageClose,
});

describe('pdf lambda handler', () => {
  beforeEach(() => {
    vi.resetModules();
    vi.unstubAllEnvs();
    vi.clearAllMocks();
    pagePdf.mockResolvedValue(Buffer.from('%PDF generated by test'));
    pageClose.mockResolvedValue(undefined);
    browserClose.mockResolvedValue(undefined);
    browserNewPage.mockResolvedValue(makePage());
    puppeteerLaunch.mockResolvedValue({
      newPage: browserNewPage,
      close: browserClose,
    });
  });

  it('returns the warmup response without launching Chromium', async () => {
    const { handler } = await import('./handler');

    await expect(handler({ warmup: true })).resolves.toEqual({
      statusCode: 200,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ message: 'PDF Lambda warmup successful' }),
    });

    expect(puppeteerLaunch).not.toHaveBeenCalled();
  });

  it('rejects requests without cvData before launching Chromium', async () => {
    const { handler } = await import('./handler');

    const response = await handler({ body: JSON.stringify({ template: 'professional' }) });

    expect(response.statusCode).toBe(400);
    expect(response.headers).toEqual({ 'Content-Type': 'application/json' });
    expect(JSON.parse(response.body)).toEqual({ error: 'Missing or invalid cvData' });
    expect(puppeteerLaunch).not.toHaveBeenCalled();
  });

  it('generates a base64 PDF response for a valid CV payload', async () => {
    const { handler } = await import('./handler');

    const response = await handler({
      body: JSON.stringify({
        template: 'professional',
        watermark: false,
        cvData: {
          personalInfo: {
            fullName: 'Test User',
            email: 'test@example.com',
            phone: '0771234567',
            summary: 'A concise profile.',
          },
          experience: [],
          education: [],
          skills: [{ name: 'TypeScript', level: 5 }],
          sectionOrder: ['summary', 'experience', 'education', 'skills'],
          themeColor: '#2563eb',
          fontFamily: 'Inter',
        },
      }),
    });

    expect(response.statusCode).toBe(200);
    expect(response.isBase64Encoded).toBe(true);
    expect(response.headers).toMatchObject({
      'Content-Type': 'application/pdf',
      'Content-Disposition': 'attachment; filename="resume.pdf"',
      'X-PDF-Template-Source': 'built-in',
      'X-PDF-Lambda-Build': expect.any(String),
    });
    expect(Buffer.from(response.body, 'base64').toString('utf8')).toBe('%PDF generated by test');
    expect(puppeteerLaunch).toHaveBeenCalledTimes(1);
    expect(browserNewPage).toHaveBeenCalledTimes(1);
    expect(pagePdf).toHaveBeenCalledWith({
      format: 'A4',
      printBackground: true,
      margin: { top: '0', right: '0', bottom: '0', left: '0' },
    });
    expect(pageClose).toHaveBeenCalledTimes(1);
    expect(browserClose).toHaveBeenCalledTimes(1);
  });

  it('allows the sanitized profile image request while blocking unrelated URLs', async () => {
    const profileImage = 'https://api.example.com/api/cv-assets/user-1/photo.webp';
    const { handler } = await import('./handler');

    const response = await handler({
      cvData: {
        personalInfo: { fullName: 'Test User' },
        profileImage,
        experience: [],
        education: [],
        skills: [],
      },
      template: 'professional',
    });

    expect(response.statusCode).toBe(200);
    const requestHandler = pageOn.mock.calls.find(([event]) => event === 'request')?.[1];
    expect(requestHandler).toBeTypeOf('function');

    const profileRequest = { url: () => profileImage, redirectChain: () => [], continue: vi.fn(), abort: vi.fn() };
    const redirectedProfileRequest = {
      url: () => 'https://cdn.example.com/profile-photo.webp',
      redirectChain: () => [{ url: () => profileImage }],
      continue: vi.fn(),
      abort: vi.fn(),
    };
    const unrelatedRequest = {
      url: () => 'https://example.com/tracker.png',
      redirectChain: () => [],
      continue: vi.fn(),
      abort: vi.fn(),
    };
    requestHandler(profileRequest);
    requestHandler(redirectedProfileRequest);
    requestHandler(unrelatedRequest);

    expect(profileRequest.continue).toHaveBeenCalledTimes(1);
    expect(profileRequest.abort).not.toHaveBeenCalled();
    expect(redirectedProfileRequest.continue).toHaveBeenCalledTimes(1);
    expect(redirectedProfileRequest.abort).not.toHaveBeenCalled();
    expect(unrelatedRequest.abort).toHaveBeenCalledTimes(1);
    expect(unrelatedRequest.continue).not.toHaveBeenCalled();
  });

  it('returns a 500 JSON response when Chromium PDF rendering fails', async () => {
    pagePdf.mockRejectedValueOnce(new Error('Chromium crashed'));
    const { handler } = await import('./handler');

    const response = await handler({
      cvData: {
        personalInfo: { fullName: 'Test User' },
        experience: [],
        education: [],
        skills: [],
      },
      template: 'professional',
    });

    expect(response.statusCode).toBe(500);
    expect(response.headers).toEqual({ 'Content-Type': 'application/json' });
    expect(JSON.parse(response.body)).toEqual({
      error: 'Failed to generate PDF',
      details: 'Chromium crashed',
    });
    expect(pageClose).toHaveBeenCalledTimes(1);
    expect(browserClose).toHaveBeenCalledTimes(1);
  });
});
